package slotwindows

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"path/filepath"
	"strings"
)

const SessionShellRelativePath = "session-shell.ps1"

var (
	ErrProfilePolicy          = errors.New("slotwindows: profile policy rejected")
	ErrProfilePolicyPath      = errors.New("slotwindows: session shell path rejected")
	ErrProfilePolicyCommand   = errors.New("slotwindows: session shell command rejected")
	ErrProfilePolicySignature = errors.New("slotwindows: session shell signature rejected")
	ErrProfilePolicyRegistry  = errors.New("slotwindows: profile policy registry update failed")
	ErrProfileBootstrap       = errors.New("slotwindows: profile bootstrap failed")
)

// ProfilePolicy contains no caller-selected executable, script, command, or
// profile path. The service derives the only script path from its verified
// runtime root.
type ProfilePolicy struct {
	RuntimeRoot string `json:"runtime_root"`
}

// NewProfilePolicy rejects traversal before deriving the fixed script path.
func NewProfilePolicy(runtimeRoot string) (ProfilePolicy, error) {
	if err := validatePolicyRoot(runtimeRoot); err != nil {
		return ProfilePolicy{}, err
	}
	return ProfilePolicy{RuntimeRoot: filepath.Clean(runtimeRoot)}, nil
}

// ParseProfilePolicy accepts the narrow persisted/configuration shape and
// rejects unknown fields so a future caller cannot smuggle an executable or
// command into the policy boundary.
func ParseProfilePolicy(data []byte) (ProfilePolicy, error) {
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	var policy ProfilePolicy
	if err := decoder.Decode(&policy); err != nil {
		return ProfilePolicy{}, fmt.Errorf("%w: %v", ErrProfilePolicy, err)
	}
	var trailing any
	if err := decoder.Decode(&trailing); err != io.EOF {
		return ProfilePolicy{}, ErrProfilePolicy
	}
	return NewProfilePolicy(policy.RuntimeRoot)
}

func (p ProfilePolicy) ScriptPath() string {
	return filepath.Join(p.RuntimeRoot, SessionShellRelativePath)
}

// ShellCommand is the exact Winlogon value. PowerShell 5.1 is deliberately
// invoked with no profile, no command text, and no execution-policy bypass.
func (p ProfilePolicy) ShellCommand() (string, error) {
	if err := validatePolicyRoot(p.RuntimeRoot); err != nil {
		return "", err
	}
	path := p.ScriptPath()
	if err := validateSessionShellPath(p.RuntimeRoot, path); err != nil {
		return "", err
	}
	return `powershell.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy AllSigned -File "` + path + `"`, nil
}

// ValidateSessionShellCommand accepts only the command generated by this
// boundary. It is useful when inspecting a target user's existing hive.
func ValidateSessionShellCommand(runtimeRoot, command string) error {
	policy, err := NewProfilePolicy(runtimeRoot)
	if err != nil {
		return err
	}
	want, err := policy.ShellCommand()
	if err != nil || command != want || strings.Contains(command, "-Command") || strings.Contains(command, "Bypass") {
		return ErrProfilePolicyCommand
	}
	return nil
}

func validatePolicyRoot(root string) error {
	cleanRoot := filepath.Clean(root)
	if root == "" || !filepath.IsAbs(root) || filepath.Dir(cleanRoot) == cleanRoot || strings.ContainsAny(root, "\x00\r\n") || hasTraversalComponent(root) {
		return ErrProfilePolicyPath
	}
	return nil
}

func validateSessionShellPath(root, path string) error {
	if err := validatePolicyRoot(root); err != nil || path == "" || !filepath.IsAbs(path) || hasTraversalComponent(path) || strings.ContainsAny(path, "\x00\r\n\"") {
		return ErrProfilePolicyPath
	}
	cleanRoot := filepath.Clean(root)
	cleanPath := filepath.Clean(path)
	rel, err := filepath.Rel(cleanRoot, cleanPath)
	if err != nil || rel != SessionShellRelativePath {
		return ErrProfilePolicyPath
	}
	return nil
}

func hasTraversalComponent(path string) bool {
	for _, part := range strings.FieldsFunc(path, func(r rune) bool { return r == '/' || r == '\\' }) {
		if part == ".." {
			return true
		}
	}
	return false
}
