package environment

import (
	"crypto/ed25519"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"sort"
	"strings"
)

// LoadTrustStore reads deployment-provided public signer keys. The file is
// data-only and may contain either base64 or hexadecimal Ed25519 public keys;
// private key material is never accepted by this boundary.
func LoadTrustStore(path string) (TrustStore, error) {
	if strings.TrimSpace(path) == "" || !filepathIsAbsoluteClean(path) {
		return nil, ErrInvalidPath
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var raw map[string]string
	dec := json.NewDecoder(strings.NewReader(string(data)))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&raw); err != nil {
		return nil, fmt.Errorf("environment: invalid trust store: %w", err)
	}
	var trailing any
	if err := dec.Decode(&trailing); err != io.EOF {
		return nil, fmt.Errorf("environment: trust store has trailing content")
	}
	if len(raw) == 0 {
		return nil, errors.New("environment: trust store is empty")
	}
	keys := make(TrustStore, len(raw))
	for signer, encoded := range raw {
		if !validToken(signer, 256) {
			return nil, ErrUntrustedSigner
		}
		key, err := decodePublicKey(encoded)
		if err != nil {
			return nil, fmt.Errorf("environment: invalid public key for signer %q", signer)
		}
		keys[signer] = key
	}
	return keys, nil
}

func decodePublicKey(value string) (ed25519.PublicKey, error) {
	value = strings.TrimSpace(value)
	if value == "" {
		return nil, ErrInvalidSignature
	}
	if decoded, err := base64.StdEncoding.DecodeString(value); err == nil && len(decoded) == ed25519.PublicKeySize {
		return ed25519.PublicKey(decoded), nil
	}
	decoded, err := hex.DecodeString(value)
	if err != nil || len(decoded) != ed25519.PublicKeySize {
		return nil, ErrInvalidSignature
	}
	return ed25519.PublicKey(decoded), nil
}

// filepathIsAbsoluteClean is kept local so this package's trust-file loader
// does not accept paths whose spelling can escape the deployment boundary.
func filepathIsAbsoluteClean(path string) bool {
	if strings.TrimSpace(path) != path || strings.ContainsAny(path, "\x00\r\n") {
		return false
	}
	// Trust-store paths are generated by the service from its data directory;
	// requiring a rooted path here prevents accidental relative lookup.
	return len(path) > 0 && (path[0] == '/' || (len(path) >= 3 && path[1] == ':' && (path[2] == '/' || path[2] == '\\')))
}

// sortedSignerNames exists for deterministic diagnostics and tests without
// exposing key material.
func sortedSignerNames(store TrustStore) []string {
	result := make([]string, 0, len(store))
	for signer := range store {
		result = append(result, signer)
	}
	sort.Strings(result)
	return result
}
