#!/usr/bin/env bash
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
fail() { echo "build contract validation failed: $1" >&2; exit 1; }

for target in windows-amd64 linux-amd64 linux-arm64 darwin-arm64; do
  grep -Fq "$target" "$repo_root/scripts/build.sh" || fail "build.sh misses $target"
  grep -Fq "$target" "$repo_root/scripts/build.ps1" || fail "build.ps1 misses $target"
  grep -Fq "$target" "$repo_root/scripts/package.ps1" || fail "package.ps1 misses $target"
done

[ -f "$repo_root/go.mod" ] || fail "go.mod is missing"
[ -f "$repo_root/browser-worker/package.json" ] || fail "browser worker package manifest is missing"
[ -f "$repo_root/browser-worker/package-lock.json" ] || fail "browser worker lockfile is missing"
[ -f "$repo_root/browser-worker/src/headless.mjs" ] || fail "headless worker is missing"
[ -f "$repo_root/browser-worker/src/headless-adapter.mjs" ] || fail "headless adapter is missing"
[ -f "$repo_root/browser-worker/src/local-test-page.html" ] || fail "local test page is missing"
[ -f "$repo_root/browser-worker/test/protocol-harness.mjs" ] || fail "browser protocol test harness is missing"
[ -f "$repo_root/browser-runtime/Cargo.toml" ] || fail "browser runtime Cargo manifest is missing"
[ -f "$repo_root/browser-runtime/Cargo.lock" ] || fail "browser runtime Cargo lockfile is missing"
[ -f "$repo_root/cmd/launcher/main.go" ] || fail "launcher command is missing"
[ -f "$repo_root/internal/automation/contract.go" ] || fail "automation contract is missing"
[ -f "$repo_root/internal/automation/protocol.go" ] || fail "automation protocol is missing"
[ -f "$repo_root/internal/plugin/process.go" ] || fail "plugin process boundary is missing"
[ -f "$repo_root/internal/plugin/client.go" ] || fail "plugin protocol client is missing"
[ -f "$repo_root/internal/launcher/update.go" ] || fail "launcher update checker is missing"
[ -f "$repo_root/internal/launcher/repair.go" ] || fail "launcher resource repairer is missing"
[ -f "$repo_root/internal/launcher/manager.go" ] || fail "launcher component/plugin manager is missing"
[ -f "$repo_root/internal/launcher/settings.go" ] || fail "launcher settings store is missing"
[ -f "$repo_root/internal/launcher/lock.go" ] || fail "launcher operation lock is missing"
[ -f "$repo_root/internal/launcher/service.go" ] || fail "launcher service controller is missing"
[ -f "$repo_root/internal/launcher/manager_test.go" ] || fail "launcher manager tests are missing"
[ -f "$repo_root/internal/launcher/settings_test.go" ] || fail "launcher settings tests are missing"
[ -f "$repo_root/internal/launcher/lock_test.go" ] || fail "launcher lock tests are missing"
[ -f "$repo_root/internal/launcher/service_test.go" ] || fail "launcher service tests are missing"
[ -f "$repo_root/internal/matrix/client.go" ] || fail "Matrix HTTP client is missing"
[ -f "$repo_root/internal/health/check.go" ] || fail "health checker is missing"
[ -f "$repo_root/internal/store/restore.go" ] || fail "store restore boundary is missing"
[ -f "$repo_root/deploy/README.md" ] || fail "deployment example is missing"
[ -f "$repo_root/plugins/bettergi/README.md" ] || fail "BetterGI plugin boundary is missing"
[ -f "$repo_root/scripts/generate_release_manifest.py" ] || fail "release manifest generator is missing"
[ -x "$repo_root/scripts/generate_release_index.py" ] || fail "release index generator is missing"
[ -x "$repo_root/scripts/validate_release_index.py" ] || fail "release index validator is missing"
[ -f "$repo_root/.github/workflows/chuzi-build.yml" ] || fail "build workflow is missing"
[ -f "$repo_root/.github/workflows/release-retry.yml" ] || fail "stable release retry workflow is missing"
[ -f "$repo_root/releases/README.md" ] || fail "release notes guidance is missing"
[ -x "$repo_root/scripts/generate_release_attestation.sh" ] || fail "release attestation generator is missing"
[ -x "$repo_root/scripts/sign_release_attestation.sh" ] || fail "release attestation signer is missing"
[ -x "$repo_root/scripts/verify_release_bundle.sh" ] || fail "release bundle verifier is missing"
[ -x "$repo_root/scripts/test_release_signing.sh" ] || fail "release signing test is missing"
[ -x "$repo_root/scripts/test_nightly_package.sh" ] || fail "nightly package test is missing"
[ -x "$repo_root/scripts/test_nightly_artifact_validator.sh" ] || fail "nightly artifact validator test is missing"
[ -x "$repo_root/scripts/accept_nightly_run.sh" ] || fail "nightly consumer acceptance script is missing"
[ -x "$repo_root/scripts/validate_release_retry_run.sh" ] || fail "release retry validator is missing"
[ -x "$repo_root/scripts/validate_nightly_artifact.py" ] || fail "nightly artifact validator is missing"
[ -x "$repo_root/scripts/test_launcher_consumer.sh" ] || fail "launcher consumer acceptance test is missing"
grep -Fq 'TestLauncherConsumerFlow' "$repo_root/cmd/launcher/consumer_test.go" || fail "launcher consumer flow test is missing"

grep -Fq 'name: chuzi-build' "$repo_root/.github/workflows/chuzi-build.yml" || fail "aggregate build check is missing"
grep -Eq 'actions/checkout@[0-9a-f]{40}' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow action is not pinned"
grep -Fq 'cargo test --locked --manifest-path browser-runtime/Cargo.toml' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses browser runtime tests"
grep -Fq 'chuzi-browser-runtime' "$repo_root/scripts/build.sh" || fail "build.sh misses Rust helper"
grep -Fq 'chuzi-browser-runtime' "$repo_root/scripts/build.ps1" || fail "build.ps1 misses Rust helper"
grep -Fq 'browserRuntime' "$repo_root/scripts/build.sh" || fail "build.sh manifest misses runtime backend"
grep -Fq 'browserRuntime' "$repo_root/scripts/build.ps1" || fail "build.ps1 manifest misses runtime backend"
grep -Fq 'desktop-webview' "$repo_root/scripts/build.sh" || fail "build.sh misses desktop feature"
grep -Fq 'desktop-webview' "$repo_root/scripts/build.ps1" || fail "build.ps1 misses desktop feature"
grep -Fq 'Test native browser runtime helper contract' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses desktop helper contract"
grep -Fq 'linux-amd64) goos=linux; goarch=amd64; binary=chuzi; runtime_backend=wry-desktop; runtime_features=desktop-webview' "$repo_root/scripts/build.sh" || fail "build.sh keeps Linux amd64 deferred"
grep -Fq 'linux-arm64) goos=linux; goarch=arm64; binary=chuzi; runtime_backend=wry-desktop; runtime_features=desktop-webview' "$repo_root/scripts/build.sh" || fail "build.sh keeps Linux arm64 deferred"
grep -Fq 'Smoke test Linux WebKitGTK on X11' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses Linux X11 smoke test"
grep -Fq 'Smoke test Linux WebKitGTK on Wayland' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses Linux Wayland smoke test"
grep -Fq 'headless-browser-command' "$repo_root/cmd/service/main.go" || fail "service misses headless browser command option"
grep -Fq 'browser-runtime.headless-cdp' "$repo_root/browser-worker/src/headless.mjs" || fail "headless worker capability is missing"
grep -Fq 'chuzi.adapter/v1' "$repo_root/browser-worker/src/headless-adapter.mjs" || fail "headless adapter protocol is missing"
grep -Fq 'genshin.cloudgame.session_probe' "$repo_root/browser-worker/src/headless-adapter.mjs" || fail "Genshin Cloud Game operation is missing"
grep -Fq 'https://ys.mihoyo.com/cloud/#/' "$repo_root/browser-worker/src/headless-adapter.mjs" || fail "Genshin Cloud Game endpoint is missing"
grep -Fq 'genshin-cloudgame@1' "$repo_root/browser-worker/scripts/build.mjs" || fail "Genshin Cloud Game capability is missing"
grep -Fq 'local.test_page_probe' "$repo_root/browser-worker/src/headless-adapter.mjs" || fail "headless adapter operation is missing"
grep -Fq 'local-test-page.html' "$repo_root/browser-worker/src/headless-adapter.mjs" || fail "headless adapter test page is missing"
grep -Fq 'process.stdin.resume()' "$repo_root/browser-worker/src/headless-adapter.mjs" || fail "headless adapter stdin is not kept alive"
grep -Fq 'node --test --test-concurrency=1 --test-reporter=spec test/headless-adapter.test.mjs test/worker.test.mjs' "$repo_root/browser-worker/package.json" || fail "browser worker tests are not in package test command"
grep -Fq 'CHUZI_TEST_DEBUG' "$repo_root/browser-worker/test/protocol-harness.mjs" || fail "browser protocol test diagnostics are not gated"
grep -Fq 'protocol_trace=' "$repo_root/browser-worker/test/protocol-harness.mjs" || fail "protocol test trace diagnostics are missing"
grep -Fq 'stderr_tail=' "$repo_root/browser-worker/test/protocol-harness.mjs" || fail "protocol test stderr diagnostics are missing"
grep -Fq 'waitReportIntervalMs' "$repo_root/browser-worker/test/protocol-harness.mjs" || fail "protocol wait diagnostics are missing"
grep -Fq 'chuzi.adapter/v1' "$repo_root/internal/automation/contract.go" || fail "adapter protocol version is missing"
grep -Fq 'LaunchMode' "$repo_root/internal/plugin/process.go" || fail "plugin launch modes are missing"
grep -Fq 'chuzi-launcher' "$repo_root/scripts/build.sh" || fail "build.sh misses launcher"
grep -Fq 'schedule:' "$repo_root/.github/workflows/chuzi-build.yml" || fail "nightly schedule is missing"
grep -Fq 'workflow_dispatch:' "$repo_root/.github/workflows/chuzi-build.yml" || fail "manual nightly trigger is missing"
grep -Fq "tags: ['v*.*.*']" "$repo_root/.github/workflows/chuzi-build.yml" || fail "formal release tag trigger is missing"
grep -Fq 'actions/upload-artifact@' "$repo_root/.github/workflows/chuzi-build.yml" || fail "nightly artifact upload is missing"
grep -Fq 'generate_release_manifest.py' "$repo_root/scripts/build.ps1" || fail "build.ps1 misses release manifest generation"
grep -Fq 'release-manifest.json' "$repo_root/scripts/package.sh" || fail "package.sh misses release manifest sidecar"
grep -Fq 'release-manifest.json' "$repo_root/scripts/package.ps1" || fail "package.ps1 misses release manifest sidecar"
grep -Fq 'generate_release_index.py' "$repo_root/scripts/package.sh" || fail "package.sh misses release index"
grep -Fq 'generate_release_index.py' "$repo_root/scripts/package.ps1" || fail "package.ps1 misses release index"
grep -Fq 'Remove-Item -Force $componentArtifact' "$repo_root/scripts/package.ps1" || fail "package.ps1 does not replace stale component archives"
grep -Fq 'release-index' "$repo_root/cmd/launcher/main.go" || fail "launcher misses network release index"
grep -Fq 'initialize-complete' "$repo_root/cmd/launcher/main.go" || fail "launcher misses initialization completion"
grep -Fq 'NetworkComponentManager' "$repo_root/internal/launcher/network.go" || fail "network component manager is missing"
grep -Fq 'nightly-${GITHUB_RUN_NUMBER}-${GITHUB_SHA:0:12}' "$repo_root/.github/workflows/chuzi-build.yml" || fail "nightly version misses commit hash"
grep -Fq 'index.json' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses release index upload"
grep -Fq 'Verify Unix artifact checksums' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses Unix checksum verification"
grep -Fq 'stable-release:' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses stable release job"
grep -Fq 'workflow_dispatch:' "$repo_root/.github/workflows/release-retry.yml" || fail "release retry workflow misses manual trigger"
grep -Fq 'validate_release_retry_run.sh' "$repo_root/.github/workflows/release-retry.yml" || fail "release retry workflow misses source run validation"
grep -Fq 'gh release create' "$repo_root/.github/workflows/release-retry.yml" || fail "release retry workflow misses GitHub release publication"
grep -Fq 'git fetch --force --no-tags origin "$tag_ref:$tag_ref"' "$repo_root/.github/workflows/chuzi-build.yml" || fail "stable release does not restore annotated tag ref"
grep -Fq 'git cat-file -e "$tag_ref^{tag}"' "$repo_root/.github/workflows/chuzi-build.yml" || fail "stable release does not require annotated tag object"
grep -Fq 'generate_release_attestation.sh' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses release attestation generation"
grep -Fq 'sign_release_attestation.sh' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses release attestation signing"
grep -Fq 'verify_release_bundle.sh' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses release bundle verification"
grep -Fq 'checksum_command=(sha256sum -c)' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses Linux checksum verifier"
grep -Fq 'checksum_command=(shasum -a 256 -c)' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses macOS checksum verifier"
grep -Fq 'run_phase '\''go-test'\'' go test -count=1 -v ./...' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses verbose Go contract test"
grep -Fq 'debug_watchdog' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses contract test diagnostics watchdog"
grep -Fq "dump_debug_state >&2" "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses failure-time contract diagnostics"
grep -Fq 'test_nightly_package.sh' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses nightly package contract"
grep -Fq 'test_nightly_artifact_validator.sh' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses nightly artifact validator contract"
grep -Fq 'test_launcher_consumer.sh' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses launcher consumer acceptance"

echo "build contract validation passed"
