#!/usr/bin/env bash
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
fail() { echo "build contract validation failed: $1" >&2; exit 1; }

for target in windows-amd64 linux-amd64 linux-arm64 darwin-arm64; do
  grep -Fq "$target" "$repo_root/scripts/build.sh" || fail "build.sh misses $target"
  grep -Fq "$target" "$repo_root/scripts/build.ps1" || fail "build.ps1 misses $target"
  grep -Fq "$target" "$repo_root/scripts/package.ps1" || fail "package.ps1 misses $target"
done

[ -f "$repo_root/go.mod" ] || fail "go.mod is missing"
[ -f "$repo_root/browser-worker/package.json" ] || fail "browser worker package manifest is missing"
[ -f "$repo_root/browser-worker/package-lock.json" ] || fail "browser worker lockfile is missing"
[ -f "$repo_root/browser-worker/src/headless.mjs" ] || fail "headless worker is missing"
[ -f "$repo_root/browser-worker/src/headless-adapter.mjs" ] || fail "headless adapter is missing"
[ -f "$repo_root/browser-worker/src/local-test-page.html" ] || fail "local test page is missing"
[ -f "$repo_root/browser-worker/test/protocol-harness.mjs" ] || fail "browser protocol test harness is missing"
[ -f "$repo_root/cmd/launcher/main.go" ] || fail "launcher command is missing"
[ -f "$repo_root/ui/windows/Cargo.toml" ] || fail "Windows Slint UI manifest is missing"
[ -f "$repo_root/ui/windows/Cargo.lock" ] || fail "Windows Slint UI lockfile is missing"
[ -f "$repo_root/ui/windows/build.rs" ] || fail "Windows Slint build script is missing"
[ -f "$repo_root/ui/windows/src/main.rs" ] || fail "Windows Slint UI entry point is missing"
[ -f "$repo_root/ui/windows/ui/main.slint" ] || fail "Windows Slint markup is missing"
[ -x "$repo_root/scripts/analyze_rdp_perf.py" ] || fail "RDP performance analyzer is missing or not executable"
[ -x "$repo_root/scripts/test_rdp_perf_analysis.sh" ] || fail "RDP performance analyzer test is missing or not executable"
[ -f "$repo_root/scripts/build_windows_slint.ps1" ] || fail "Windows Slint build script is missing"
[ -f "$repo_root/internal/coretransport/listener_windows_test.go" ] || fail "Windows Core transport test is missing"
[ -f "$repo_root/internal/automation/contract.go" ] || fail "automation contract is missing"
[ -f "$repo_root/internal/automation/protocol.go" ] || fail "automation protocol is missing"
[ -f "$repo_root/internal/plugin/process.go" ] || fail "plugin process boundary is missing"
[ -f "$repo_root/internal/plugin/client.go" ] || fail "plugin protocol client is missing"
[ -f "$repo_root/internal/launcher/update.go" ] || fail "launcher update checker is missing"
[ -f "$repo_root/internal/launcher/repair.go" ] || fail "launcher resource repairer is missing"
[ -f "$repo_root/internal/launcher/manager.go" ] || fail "launcher component/plugin manager is missing"
[ -f "$repo_root/internal/launcher/settings.go" ] || fail "launcher settings store is missing"
[ -f "$repo_root/internal/launcher/lock.go" ] || fail "launcher operation lock is missing"
[ -f "$repo_root/internal/launcher/service.go" ] || fail "launcher service controller is missing"
[ -f "$repo_root/internal/launcher/manager_test.go" ] || fail "launcher manager tests are missing"
[ -f "$repo_root/internal/launcher/settings_test.go" ] || fail "launcher settings tests are missing"
[ -f "$repo_root/internal/launcher/lock_test.go" ] || fail "launcher lock tests are missing"
[ -f "$repo_root/internal/launcher/service_test.go" ] || fail "launcher service tests are missing"
[ -f "$repo_root/internal/matrix/client.go" ] || fail "Matrix HTTP client is missing"
[ -f "$repo_root/internal/health/check.go" ] || fail "health checker is missing"
[ -f "$repo_root/internal/store/restore.go" ] || fail "store restore boundary is missing"
[ -f "$repo_root/deploy/README.md" ] || fail "deployment example is missing"
[ -f "$repo_root/plugins/bettergi/README.md" ] || fail "BetterGI plugin boundary is missing"
[ -f "$repo_root/scripts/generate_release_manifest.py" ] || fail "release manifest generator is missing"
[ -x "$repo_root/scripts/generate_release_index.py" ] || fail "release index generator is missing"
[ -x "$repo_root/scripts/validate_release_index.py" ] || fail "release index validator is missing"
[ -f "$repo_root/.github/workflows/chuzi-build.yml" ] || fail "build workflow is missing"
[ -f "$repo_root/.github/workflows/release-retry.yml" ] || fail "stable release retry workflow is missing"
[ -f "$repo_root/releases/README.md" ] || fail "release notes guidance is missing"
[ -x "$repo_root/scripts/generate_release_attestation.sh" ] || fail "release attestation generator is missing"
[ -x "$repo_root/scripts/sign_release_attestation.sh" ] || fail "release attestation signer is missing"
[ -x "$repo_root/scripts/verify_release_bundle.sh" ] || fail "release bundle verifier is missing"
[ -x "$repo_root/scripts/test_release_signing.sh" ] || fail "release signing test is missing"
[ -x "$repo_root/scripts/test_nightly_package.sh" ] || fail "nightly package test is missing"
[ -x "$repo_root/scripts/test_nightly_artifact_validator.sh" ] || fail "nightly artifact validator test is missing"
[ -x "$repo_root/scripts/test_release_catalog.sh" ] || fail "release catalog test is missing"
[ -x "$repo_root/scripts/publish_release_catalog.py" ] || fail "release catalog publisher is missing"
[ -x "$repo_root/scripts/resolve_release_channel.py" ] || fail "release channel resolver is missing"
[ -x "$repo_root/scripts/test_release_channels.sh" ] || fail "release channel contract test is missing"
[ -x "$repo_root/scripts/accept_nightly_run.sh" ] || fail "nightly consumer acceptance script is missing"
[ -x "$repo_root/scripts/accept_test_run.sh" ] || fail "test consumer acceptance script is missing"
[ -x "$repo_root/scripts/validate_release_retry_run.sh" ] || fail "release retry validator is missing"
[ -x "$repo_root/scripts/validate_nightly_artifact.py" ] || fail "nightly artifact validator is missing"
[ -x "$repo_root/scripts/test_launcher_consumer.sh" ] || fail "launcher consumer acceptance test is missing"
[ -x "$repo_root/scripts/build_go_target.sh" ] || fail "parallel Go target builder is missing"
[ -x "$repo_root/scripts/build_worker.sh" ] || fail "parallel worker builder is missing"
[ -x "$repo_root/scripts/assemble_target.sh" ] || fail "Unix target assembler is missing"
[ -f "$repo_root/scripts/assemble_target.ps1" ] || fail "Windows target assembler is missing"
[ -f "$repo_root/.github/workflows/chuzi-pr.yml" ] || fail "pull request workflow is missing"
grep -Fq 'TestLauncherConsumerFlow' "$repo_root/cmd/launcher/consumer_test.go" || fail "launcher consumer flow test is missing"

grep -Fq 'name: chuzi-build' "$repo_root/.github/workflows/chuzi-build.yml" || fail "aggregate build check is missing"
grep -Fq 'scripts/test_rdp_perf_analysis.sh' "$repo_root/.github/workflows/chuzi-build.yml" || fail "build workflow misses RDP performance analyzer test"
grep -Eq 'actions/checkout@[0-9a-f]{40}' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow action is not pinned"
grep -Fq 'branches: [main]' "$repo_root/.github/workflows/chuzi-build.yml" || fail "main integration build trigger is missing"
if grep -Eq '^[[:space:]]*pull_request:' "$repo_root/.github/workflows/chuzi-build.yml"; then
  fail "full build workflow must not run on pull requests"
fi
grep -Fq 'pull_request:' "$repo_root/.github/workflows/chuzi-pr.yml" || fail "pull request workflow trigger is missing"
grep -Fq 'scripts/test_rdp_perf_analysis.sh' "$repo_root/.github/workflows/chuzi-pr.yml" || fail "pull request workflow misses RDP performance analyzer test"
grep -Fq 'name: chuzi-build' "$repo_root/.github/workflows/chuzi-pr.yml" || fail "pull request required check is missing"
grep -Fq 'cancel-in-progress: true' "$repo_root/.github/workflows/chuzi-pr.yml" || fail "pull request cancellation is missing"
grep -Eq 'actions/checkout@[0-9a-f]{40}' "$repo_root/.github/workflows/chuzi-pr.yml" || fail "pull request action is not pinned"
if grep -Eq 'go build|run build|build_go_target|build_worker|build_runtime' "$repo_root/.github/workflows/chuzi-pr.yml"; then
  fail "pull request workflow must not run release compilation"
fi
if rg -n -i '(browser-runtime/|chuzi-browser-runtime|wry|desktop-webview|desktop-runtime|runtime_build|rust_checks|build_runtime|test_desktop_runtime)' "$repo_root/.github" "$repo_root/cmd" "$repo_root/internal"; then
  fail "deprecated Rust/Wry runtime path remains in implementation or build files"
fi
grep -Fq 'headless-browser-command' "$repo_root/cmd/service/main.go" || fail "service misses headless browser command option"
grep -Fq 'browser-runtime.headless-cdp' "$repo_root/browser-worker/src/headless.mjs" || fail "headless worker capability is missing"
grep -Fq 'chuzi.adapter/v1' "$repo_root/browser-worker/src/headless-adapter.mjs" || fail "headless adapter protocol is missing"
grep -Fq 'genshin.cloudgame.session_probe' "$repo_root/browser-worker/src/headless-adapter.mjs" || fail "Genshin Cloud Game operation is missing"
grep -Fq 'https://ys.mihoyo.com/cloud/#/' "$repo_root/browser-worker/src/headless-adapter.mjs" || fail "Genshin Cloud Game endpoint is missing"
grep -Fq 'genshin-cloudgame@1' "$repo_root/browser-worker/scripts/build.mjs" || fail "Genshin Cloud Game capability is missing"
grep -Fq 'local.test_page_probe' "$repo_root/browser-worker/src/headless-adapter.mjs" || fail "headless adapter operation is missing"
grep -Fq 'local-test-page.html' "$repo_root/browser-worker/src/headless-adapter.mjs" || fail "headless adapter test page is missing"
grep -Fq 'process.stdin.resume()' "$repo_root/browser-worker/src/headless-adapter.mjs" || fail "headless adapter stdin is not kept alive"
grep -Fq 'node --test --test-concurrency=1 --test-reporter=spec test/headless-adapter.test.mjs test/worker.test.mjs' "$repo_root/browser-worker/package.json" || fail "browser worker tests are not in package test command"
grep -Fq 'CHUZI_TEST_DEBUG' "$repo_root/browser-worker/test/protocol-harness.mjs" || fail "browser protocol test diagnostics are not gated"
grep -Fq 'protocol_trace=' "$repo_root/browser-worker/test/protocol-harness.mjs" || fail "protocol test trace diagnostics are missing"
grep -Fq 'stderr_tail=' "$repo_root/browser-worker/test/protocol-harness.mjs" || fail "protocol test stderr diagnostics are missing"
grep -Fq 'waitReportIntervalMs' "$repo_root/browser-worker/test/protocol-harness.mjs" || fail "protocol wait diagnostics are missing"
grep -Fq 'chuzi.adapter/v1' "$repo_root/internal/automation/contract.go" || fail "adapter protocol version is missing"
grep -Fq 'LaunchMode' "$repo_root/internal/plugin/process.go" || fail "plugin launch modes are missing"
grep -Fq 'chuzi-launcher' "$repo_root/scripts/build.sh" || fail "build.sh misses launcher"
grep -Fq 'test-*' "$repo_root/scripts/build.sh" || fail "build.sh misses test release versions"
grep -Fq 'test-' "$repo_root/scripts/build.ps1" || fail "build.ps1 misses test release versions"
grep -Fq 'test-*' "$repo_root/scripts/build_go_target.sh" || fail "build_go_target.sh misses test release versions"
grep -Fq 'schedule:' "$repo_root/.github/workflows/chuzi-build.yml" || fail "nightly schedule is missing"
grep -Fq 'workflow_dispatch:' "$repo_root/.github/workflows/chuzi-build.yml" || fail "manual nightly trigger is missing"
grep -Fq "tags: ['v*.*.*']" "$repo_root/.github/workflows/chuzi-build.yml" || fail "formal release tag trigger is missing"
grep -Fq 'actions/upload-artifact@' "$repo_root/.github/workflows/chuzi-build.yml" || fail "nightly artifact upload is missing"
grep -Fq 'generate_release_manifest.py' "$repo_root/scripts/build.ps1" || fail "build.ps1 misses release manifest generation"
grep -Fq 'release-manifest.json' "$repo_root/scripts/package.sh" || fail "package.sh misses release manifest sidecar"
grep -Fq 'release-manifest.json' "$repo_root/scripts/package.ps1" || fail "package.ps1 misses release manifest sidecar"
grep -Fq 'generate_release_index.py' "$repo_root/scripts/package.sh" || fail "package.sh misses release index"
grep -Fq 'generate_release_index.py' "$repo_root/scripts/package.ps1" || fail "package.ps1 misses release index"
grep -Fq 'Remove-Item -Force $componentArtifact' "$repo_root/scripts/package.ps1" || fail "package.ps1 does not replace stale component archives"
grep -Fq 'release-index' "$repo_root/cmd/launcher/main.go" || fail "launcher misses network release index"
grep -Fq 'initialize-complete' "$repo_root/cmd/launcher/main.go" || fail "launcher misses initialization completion"
grep -Fq 'NetworkComponentManager' "$repo_root/internal/launcher/network.go" || fail "network component manager is missing"
grep -Fq 'resolve_release_channel.py' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses centralized channel resolver"
grep -Fq 'chuzi-${{ needs.release_context.outputs.channel }}-${{ matrix.target }}' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses channel-specific artifact names"
grep -Fq 'pattern: chuzi-${{ needs.release_context.outputs.channel }}-*' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses channel-specific artifact download"
grep -Fq 'index.json' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses release index upload"
grep -Fq 'Verify Unix artifact checksums' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses Unix checksum verification"
grep -Fq 'stable-release:' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses stable release job"
grep -Fq 'publish-release-catalog:' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses release catalog publication"
grep -Fq 'inputs.channel' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses manual release channel selection"
grep -Fq 'workflow_dispatch:' "$repo_root/.github/workflows/release-retry.yml" || fail "release retry workflow misses manual trigger"
grep -Fq 'validate_release_retry_run.sh' "$repo_root/.github/workflows/release-retry.yml" || fail "release retry workflow misses source run validation"
grep -Fq 'gh release create' "$repo_root/.github/workflows/release-retry.yml" || fail "release retry workflow misses GitHub release publication"
grep -Fq 'git fetch --force --no-tags origin "$tag_ref:$tag_ref"' "$repo_root/.github/workflows/chuzi-build.yml" || fail "stable release does not restore annotated tag ref"
grep -Fq 'git cat-file -e "$tag_ref^{tag}"' "$repo_root/.github/workflows/chuzi-build.yml" || fail "stable release does not require annotated tag object"
grep -Fq 'generate_release_attestation.sh' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses release attestation generation"
grep -Fq 'sign_release_attestation.sh' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses release attestation signing"
grep -Fq 'verify_release_bundle.sh' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses release bundle verification"
grep -Fq 'checksum_command=(sha256sum -c)' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses Linux checksum verifier"
grep -Fq 'checksum_command=(shasum -a 256 -c)' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses macOS checksum verifier"
grep -Fq 'go test -count=1 -v ./...' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses verbose Go contract test"
grep -Fq 'go vet ./...' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses Go vet"
grep -Fq 'build_go_target.sh' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses parallel Go target build"
grep -Fq 'build_worker.sh' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses parallel worker build"
grep -Fq 'assemble_target.sh' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses Unix artifact assembly"
grep -Fq 'assemble_target.ps1' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses Windows artifact assembly"
grep -Fq 'artifact_integration:' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses artifact integration stage"
grep -Fq 'name: ci-worker' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses worker artifact handoff"
grep -Fq 'name: ci-go-${{ matrix.target }}' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses Go artifact handoff"
grep -Fq 'test_nightly_package.sh' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses nightly package contract"
grep -Fq 'test_nightly_artifact_validator.sh' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses nightly artifact validator contract"
grep -Fq 'test_launcher_consumer.sh' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses launcher consumer acceptance"
grep -Fq 'name: chuzi-build-windows-slint' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses Windows Slint build"
grep -Fq 'build_windows_slint.ps1' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses Windows Slint packaging"
grep -Fq 'layout_snapshot' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses Slint layout snapshot check"
grep -Fq 'i-slint-backend-testing' "$repo_root/ui/windows/Cargo.toml" || fail "Windows Slint manifest misses testing backend"
grep -Fq 'slint-lsp' "$repo_root/ui/windows/README.md" || fail "Windows Slint README misses editor diagnostics"
grep -Fq '800x600' "$repo_root/ui/windows/README.md" || fail "Windows Slint README misses compact viewport"
grep -Fq '1120x760' "$repo_root/ui/windows/README.md" || fail "Windows Slint README misses preferred viewport"
grep -Fq '1440x900' "$repo_root/ui/windows/README.md" || fail "Windows Slint README misses wide viewport"
test -f "$repo_root/ui/windows/examples/layout_snapshot.rs" || fail "Slint layout snapshot example is missing"
grep -Fq 'InstallerExe' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses Windows installer EXE mode"
grep -Fq 'name: chuzi-windows-installer-exe' "$repo_root/.github/workflows/chuzi-build.yml" || fail "workflow misses Windows installer EXE artifact"
if grep -Fq 'PackagedMsix' "$repo_root/.github/workflows/chuzi-build.yml"; then
  fail "workflow retains MSIX packaging mode"
fi
if grep -Fq 'chuzi-windows-msix' "$repo_root/.github/workflows/chuzi-build.yml"; then
  fail "workflow retains MSIX artifact"
fi
if grep -Eq '^[[:space:]]{2}windows_msix:' "$repo_root/.github/workflows/chuzi-build.yml"; then
  fail "workflow retains duplicate Windows MSIX job"
fi
if grep -Fq 'name: ci-ui-windows' "$repo_root/.github/workflows/chuzi-build.yml"; then
  fail "workflow retains obsolete unpackaged UI artifact"
fi
grep -Fq 'needs: [release_context, go_build, node_checks]' "$repo_root/.github/workflows/chuzi-build.yml" || fail "assemble target dependencies are incomplete"
grep -Fq 'ValidateSet("InstallerExe", "UnpackagedZip")' "$repo_root/scripts/build_windows_slint.ps1" || fail "Windows Slint script misses explicit packaging modes"
grep -Fq 'ISCC.exe' "$repo_root/scripts/build_windows_slint.ps1" || fail "Windows Slint script misses Inno Setup compiler"
grep -Fq 'packaging/windows/Chuzi.iss' "$repo_root/scripts/build_windows_slint.ps1" || fail "Windows Slint script misses installer definition"
grep -Fq 'OutputBaseFilename=ChuziSetup' "$repo_root/packaging/windows/Chuzi.iss" || fail "Windows installer misses stable setup filename"
grep -Fq 'Source: "{#PayloadDir}\*"' "$repo_root/packaging/windows/Chuzi.iss" || fail "Windows installer misses published payload"
grep -Fq 'UninstallDelete' "$repo_root/packaging/windows/Chuzi.iss" || fail "Windows installer misses uninstall cleanup"
grep -Fq 'KeepUserData' "$repo_root/packaging/windows/Chuzi.iss" || fail "Windows uninstall misses user-data retention option"
grep -Fq 'Check: ShouldDeleteUserData' "$repo_root/packaging/windows/Chuzi.iss" || fail "Windows uninstall data cleanup must use a check function"
grep -Fq 'function ShouldDeleteUserData(): Boolean;' "$repo_root/packaging/windows/Chuzi.iss" || fail "Windows uninstall data cleanup check function is missing"
grep -Fq 'prepare_presentmon.ps1' "$repo_root/scripts/assemble_target.ps1" || fail "Windows target assembly misses PresentMon preparation"
grep -Fq 'PresentMon.exe' "$repo_root/scripts/generate_release_manifest.py" || fail "Windows release manifest misses PresentMon component"
grep -Fq 'PresentMon-LICENSE.txt' "$repo_root/scripts/generate_release_manifest.py" || fail "Windows PresentMon component misses its license"
grep -Fq 'CorePayloadDir' "$repo_root/scripts/build_windows_slint.ps1" || fail "Windows Slint script misses Core payload staging"
grep -Fq 'CorePayload' "$repo_root/scripts/build_windows_slint.ps1" || fail "Windows Slint build misses Core payload staging"
grep -Fq 'slint::include_modules!' "$repo_root/ui/windows/src/main.rs" || fail "Windows Slint client does not include generated UI"
grep -Fq 'MainWindow' "$repo_root/ui/windows/ui/main.slint" || fail "Windows Slint shell is missing"
grep -Fq 'First-run checklist' "$repo_root/ui/windows/ui/main.slint" || fail "Windows Slint overview misses first-run checklist"
grep -Fq 'refresh-plugins' "$repo_root/ui/windows/ui/main.slint" || fail "Windows Slint plugin flow is missing"
grep -Fq 'get_account' "$repo_root/ui/windows/src/main.rs" || fail "Windows Slint client misses account lookup"
grep -Fq 'submit_request' "$repo_root/ui/windows/src/main.rs" || fail "Windows Slint client misses task submission"
grep -Fq 'cancel_request' "$repo_root/ui/windows/src/main.rs" || fail "Windows Slint client misses task cancellation"
grep -Fq 'Smoke test installed Slint client' "$repo_root/.github/workflows/chuzi-build.yml" || fail "Windows Slint workflow misses startup smoke test"
grep -Fq 'Assemble Core payload for the Slint package' "$repo_root/.github/workflows/chuzi-build.yml" || fail "Windows Slint workflow misses Core payload assembly"
grep -Fq 'core-call' "$repo_root/ui/windows/src/main.rs" || fail "Windows Slint client misses launcher Core façade"
grep -Fq 'chuzi.core/v1' "$repo_root/internal/coreapi/api.go" || fail "Core API misses API version"
grep -Fq 'EndpointPath' "$repo_root/internal/launcher/core.go" || fail "launcher Core façade misses endpoint derivation"

for obsolete in \
  "$repo_root/ui/windows/Chuzi.Native.Windows.csproj" \
  "$repo_root/ui/windows/CoreApiClient.cs" \
  "$repo_root/ui/windows/CoreServiceController.cs" \
  "$repo_root/ui/windows/LauncherClient.cs" \
  "$repo_root/ui/windows/CorePipeSmoke.csproj" \
  "$repo_root/ui/windows/CoreLifecycleSmoke.csproj" \
  "$repo_root/scripts/build_windows_ui.ps1"; do
  test ! -e "$obsolete" || fail "obsolete WinUI file remains: $obsolete"
done
if rg -n -i 'winui|microsoft\.ui\.xaml|windowsapp|setup-dotnet|build_windows_ui|CoreLifecycleSmoke|CorePipeSmoke' \
  "$repo_root/README.md" "$repo_root/docs" "$repo_root/ui" "$repo_root/.github/workflows" "$repo_root/packaging"; then
  fail "obsolete WinUI references remain outside historical CR records"
fi

echo "build contract validation passed"
